
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author BrunoMurrieta
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private Dimension size;
    private String codigo = "";
    private int width, height;
    public int segundos = 0;
    public Timer timer;

    public NewJFrame() {

        initComponents();
        size = Toolkit.getDefaultToolkit().getScreenSize();
        width = Toolkit.getDefaultToolkit().getScreenSize().width;
        height = Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height);
        this.setLayout(null);
        this.getContentPane().setBackground(new Color(60, 179, 113));

        AvisoError.setText("No se pudo escanear el \nproducto, Intente de nuevo o \npase a servicio al cliente");
        Logo.setSize(474, 285);
        Logo.setLocation(width / 4 - Logo.getWidth() / 2, height / 3 - Logo.getHeight() / 2);
        Demo.setSize(400, 300);
        Demo.setLocation(3 * width / 4 - Demo.getWidth() / 2, height / 3 - Demo.getHeight() / 2);
        Lector.setSize(217, 139);
        Lector.setLocation(width / 2 - Lector.getWidth() / 2, height - Lector.getHeight() - 50);
        Aviso.setLocation(width / 2 - Aviso.getWidth() / 2, height - Lector.getHeight() - 90);
        ErrorImg.setSize(400, 400);
        ErrorImg.setLocation(width / 2 - ErrorImg.getWidth() / 2, height / 2 - ErrorImg.getHeight() / 2 - 100);
        AvisoError.setLocation(width / 2 - AvisoError.getWidth() / 2, height / 2 - AvisoError.getHeight() + 200);
        //Cargar.setSize(200, 200);
        //Cargar.setLocation(width / 2 - Cargar.getWidth() / 2, height / 2 - Cargar.getHeight() / 2);
        ImagenP.setSize(400, 400);
        ImagenP.setLocation(width / 8, height / 2 - ImagenP.getHeight() + 100);
        Datos.setLocation(width / 2, ImagenP.getY());

        //label.setIcon(new ImageIcon(new ImageIcon("icon.png").getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT)));
        //Cargar.setIcon(new ImageIcon(new ImageIcon("img\\loading-waiting.gif").getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT)));
        Demo.setIcon(new ImageIcon(new ImageIcon("img\\LectorGif.gif").getImage().getScaledInstance(400, 300, Image.SCALE_DEFAULT)));
        Logo.setIcon(new ImageIcon(new ImageIcon("img\\SuperDelSur.png").getImage().getScaledInstance(474, 285, Image.SCALE_DEFAULT)));
        Lector.setIcon(new ImageIcon(new ImageIcon("img\\Scan.png").getImage().getScaledInstance(217, 139, Image.SCALE_DEFAULT)));
        ErrorImg.setIcon(new ImageIcon(new ImageIcon("img\\error.png").getImage().getScaledInstance(400, 400, Image.SCALE_DEFAULT)));

        //ImagenP.setIcon(new ImageIcon(new ImageIcon("img\\SuperDelSur.png").getImage().getScaledInstance(474, 285, Image.SCALE_DEFAULT)));
        ImagenP.setVisible(false);
        //Cargar.setVisible(false);
        ErrorImg.setVisible(false);
        AvisoError.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AvisoError = new javax.swing.JLabel();
        Aviso = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Lector = new javax.swing.JLabel();
        Datos = new javax.swing.JLabel();
        ImagenP = new javax.swing.JLabel();
        Demo = new javax.swing.JLabel();
        ErrorImg = new javax.swing.JLabel();
        Cargar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 179, 113));
        setUndecorated(true);
        setSize(Toolkit. getDefaultToolkit(). getScreenSize().width, Toolkit. getDefaultToolkit(). getScreenSize().height);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        AvisoError.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        AvisoError.setName(""); // NOI18N

        Aviso.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        Aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Aviso.setText("Esperando por articulo...");
        Aviso.setPreferredSize(new java.awt.Dimension(600, 25));

        Logo.setMaximumSize(new java.awt.Dimension(474, 285));
        Logo.setPreferredSize(new java.awt.Dimension(474, 285));

        Lector.setPreferredSize(new java.awt.Dimension(120, 120));

        Datos.setFont(new java.awt.Font("Lucida Console", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Demo)
                        .addGap(82, 82, 82)
                        .addComponent(ErrorImg)
                        .addGap(64, 64, 64)
                        .addComponent(Cargar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AvisoError)
                                .addGap(18, 18, 18)
                                .addComponent(Aviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(ImagenP))
                            .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvisoError)
                    .addComponent(Aviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ImagenP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Demo)
                    .addComponent(ErrorImg)
                    .addComponent(Cargar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

        //JOptionPane.showMessageDialog(null, evt.getKeyCode());
        if (evt.getKeyCode() != 10) {
            codigo += evt.getKeyChar();
        } else {
            Datos.setVisible(false);
            AvisoError.setVisible(false);
            ErrorImg.setVisible(false);
            ImagenP.setVisible(false);
            Logo.setSize(158, 95);
            Logo.setLocation(width / 4 - Logo.getWidth() / 2, height - Logo.getHeight() - 50);
            Logo.setIcon(new ImageIcon(new ImageIcon("img\\SuperDelSur.png").getImage().getScaledInstance(158, 95, Image.SCALE_DEFAULT)));
            Demo.setVisible(false);
            Aviso.setVisible(false);
            Lector.setVisible(false);
            //timer para la imagen
            try {
                Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/verificador", "root", "");
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT producto_nombre, producto_precio, producto_cantidad, producto_imagen FROM productos WHERE producto_codigo = " + codigo);

                //Aquí los índices empiezan en 1
                if (rs.next()) {
                    Demo.setVisible(false);
                    Datos.setVisible(true);
                    Lector.setVisible(true);
                    ImagenP.setVisible(true);
                    Logo.setVisible(true);
                    Aviso.setVisible(true);
                    Aviso.setText("Esperando por nuevo articulo");
                    Aviso.setLocation(width / 2 - Aviso.getWidth() / 2, height - Lector.getHeight() - 90);
                    Datos.setSize(width - Datos.getX(), 150);
                    Datos.setText("<html>Nombre: " + rs.getString(1) + "<br>Precio: " + rs.getString(2) + "<br>Cantidad en almacén: " + rs.getString(3));
                    try {
                        String path = rs.getString(4);
                        URL url = new URL(path);
                        BufferedImage image = ImageIO.read(url);
                        ImagenP.setIcon(new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(ImagenP.getWidth(), ImagenP.getHeight(), Image.SCALE_DEFAULT)));
                    } catch (Exception exp) {
                        ImagenP.setIcon(new ImageIcon(new ImageIcon("img\\placeholder.png").getImage().getScaledInstance(146, 132, Image.SCALE_DEFAULT)));
                    }
                    segundos = 0;
                    TimerInicio();
                } else {
                    MostrarError();
                }

                //JOptionPane.showMessageDialog(null, "SELECT * FROM productos WHERE producto_codigo = "+codigo);
            } catch (ClassNotFoundException e) {
                MostrarError();
            } catch (SQLException e) {
                MostrarError();
            } catch (Exception e) {
                MostrarError();
            }
            codigo = "";
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public void TimerInicio() {
        timer = new Timer(1000, new ActionListener() {      // Timer 4 seconds
            public void actionPerformed(ActionEvent e) {
                segundos++;
                if (segundos == 8) {
                    Lector.setVisible(true);
                    ImagenP.setVisible(false);
                    Logo.setSize(474, 285);
                    Logo.setLocation(width / 4 - Logo.getWidth() / 2, height / 3 - Logo.getHeight() / 2);
                    Logo.setIcon(new ImageIcon(new ImageIcon("img\\SuperDelSur.png").getImage().getScaledInstance(474, 285, Image.SCALE_DEFAULT)));
                    Demo.setVisible(true);
                    Datos.setText("");
                    Aviso.setVisible(true);
                    Aviso.setText("Esperando por articulo...");
                    Aviso.setLocation(width / 2 - Aviso.getWidth() / 2, height - Lector.getHeight() - 90);
                    ErrorImg.setVisible(false);
                    AvisoError.setVisible(false);
                    timer.stop();
                }
            }
        });
        timer.start();
    }

    public void MostrarError() {
        Lector.setVisible(true);
        ErrorImg.setVisible(true);
        Aviso.setVisible(true);
        AvisoError.setVisible(true);
        Datos.setVisible(false);
        ImagenP.setVisible(false);
        segundos = 0;
        TimerInicio();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aviso;
    private javax.swing.JLabel AvisoError;
    private javax.swing.JLabel Cargar;
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel Demo;
    private javax.swing.JLabel ErrorImg;
    private javax.swing.JLabel ImagenP;
    private javax.swing.JLabel Lector;
    private javax.swing.JLabel Logo;
    // End of variables declaration//GEN-END:variables
}
